package netdiag

import (
	"strings"
	"testing"
	"time"

	"github.com/hi-donwi/SRE-Toolkit/pkg/model"
)

func TestParseResolvConfHandlesIPv6(t *testing.T) {
	const sample = `# Generated by NetworkManager
nameserver 10.0.0.2
nameserver 2001:4860:4860::8888
; a comment
nameserver 1.1.1.1
options edns0
`

	got := parseResolvConf(sample)

	want := []string{"10.0.0.2:53", "[2001:4860:4860::8888]:53", "1.1.1.1:53"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			// Appending ":53" to a v6 literal yields an address net.Dial cannot
			// parse, silently failing every IPv6 resolver check.
			t.Errorf("resolver[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

func TestParseResolvConfFallsBackToLocalhost(t *testing.T) {
	got := parseResolvConf("# nothing but comments\noptions ndots:5\n")

	if len(got) != 1 || got[0] != "127.0.0.1:53" {
		t.Errorf("got %v, want the localhost fallback", got)
	}
}

func TestEvaluateMTUReportsUnknownWhenICMPFiltered(t *testing.T) {
	// Every probe fails because the target ignores ICMP entirely. Reporting a
	// critical VXLAN MTU fault here is a false positive: nothing was measured.
	results := []MTUCheckResult{
		{TestedMTU: 1500, Pass: false},
		{TestedMTU: 1450, Pass: false},
		{TestedMTU: 1420, Pass: false},
		{TestedMTU: 1280, Pass: false},
	}

	findings := evaluateMTU("10.0.0.1", false, results)

	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1", len(findings))
	}
	if findings[0].ID != "NET-MTU-UNKNOWN" {
		t.Errorf("ID = %s, want NET-MTU-UNKNOWN", findings[0].ID)
	}
	if findings[0].Severity != model.SeverityInfo {
		t.Errorf("severity = %s, want INFO — an unmeasurable path is not an outage", findings[0].Severity)
	}
}

func TestEvaluateMTUReportsVXLANDrop(t *testing.T) {
	results := []MTUCheckResult{
		{TestedMTU: 1500, Pass: false, PayloadBytes: 1472},
		{TestedMTU: 1450, Pass: false, PayloadBytes: 1422},
		{TestedMTU: 1420, Pass: true, PayloadBytes: 1392},
		{TestedMTU: 1280, Pass: true, PayloadBytes: 1252},
	}

	findings := evaluateMTU("10.0.0.1", true, results)

	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1", len(findings))
	}
	if findings[0].ID != "SWM-MTU-001" {
		t.Errorf("ID = %s, want SWM-MTU-001 (the catalog ID from SPEC.md)", findings[0].ID)
	}
	if findings[0].Severity != model.SeverityCritical {
		t.Errorf("severity = %s, want CRITICAL", findings[0].Severity)
	}
}

func TestEvaluateMTUIgnoresNormalTunnelMTU(t *testing.T) {
	// 1500 dropping while 1450 passes is ordinary on any tunnelled path and
	// must not be reported as a fault.
	results := []MTUCheckResult{
		{TestedMTU: 1500, Pass: false},
		{TestedMTU: 1450, Pass: true},
		{TestedMTU: 1420, Pass: true},
		{TestedMTU: 1280, Pass: true},
	}

	if findings := evaluateMTU("10.0.0.1", true, results); len(findings) != 0 {
		t.Errorf("got %d findings, want 0: %+v", len(findings), findings)
	}
}

func TestEvaluateMTUFlagsSubIPv6Minimum(t *testing.T) {
	results := []MTUCheckResult{
		{TestedMTU: 1500, Pass: false},
		{TestedMTU: 1450, Pass: false},
		{TestedMTU: 1420, Pass: false},
		{TestedMTU: 1280, Pass: false},
	}

	findings := evaluateMTU("10.0.0.1", true, results)

	var sawMinimum bool
	for _, f := range findings {
		if f.ID == "NET-MTU-001" {
			sawMinimum = true
		}
	}
	if !sawMinimum {
		t.Error("a path below the 1280-byte IPv6 minimum should be reported")
	}
}

func TestProbeTCPHandshakeReportsFailureCleanly(t *testing.T) {
	// Port 1 on localhost is reliably closed; no external network needed.
	res := ProbeTCPHandshake("127.0.0.1", 1, 500*time.Millisecond)

	if res.Port != 1 {
		t.Errorf("Port = %d, want 1", res.Port)
	}
	if res.Success {
		t.Error("expected the handshake to fail against a closed port")
	}
	if res.Error == "" {
		t.Error("Error should describe why the handshake failed")
	}
}

func TestProbeTCPHandshakeAcceptsIPv6Literal(t *testing.T) {
	// Formatting the address with "%s:%d" produces "::1:1", which is not a
	// valid address. JoinHostPort brackets it correctly.
	res := ProbeTCPHandshake("::1", 1, 500*time.Millisecond)

	if res.Error != "" && strings.Contains(res.Error, "too many colons") {
		t.Errorf("IPv6 literal was not bracketed: %s", res.Error)
	}
}

func TestBenchmarkDNSNetworked(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network-dependent DNS benchmark in -short mode")
	}

	results := BenchmarkDNS("example.com")
	if len(results) == 0 {
		t.Fatal("expected at least one nameserver result")
	}
	for _, r := range results {
		if r.Nameserver == "" {
			t.Error("every result should name its resolver")
		}
	}
}

func TestRunNetworkAuditNetworked(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network-dependent audit in -short mode")
	}

	rep := RunNetworkAudit("1.1.1.1")
	if rep == nil {
		t.Fatal("expected a report")
	}
	if len(rep.MTUResults) != 4 {
		t.Errorf("got %d MTU results, want 4", len(rep.MTUResults))
	}
	if rep.Duration <= 0 {
		t.Error("Duration should be measured, not hardcoded")
	}
	if len(rep.Findings) == 0 {
		t.Error("expected at least one finding (healthy or otherwise)")
	}
}
