package analyzer

import (
	"strings"

	"github.com/hi-donwi/SRE-Toolkit/pkg/model"
)

var standardCatalog = map[string]model.Finding{
	"HOST-DSK-001": {
		ID:         "HOST-DSK-001",
		Title:      "High Disk Space Utilization",
		TargetType: model.TargetHost,
		Category:   "Disk Utilization",
		Severity:   model.SeverityCritical,
		Resource:   "filesystem:/",
		Symptom:    "Filesystem disk space usage has exceeded warning (80%) or critical (90%) thresholds.",
		RootCause:  "Application log accumulation, unrotated core dumps, lingering container layers, or bloated data directories.",
		RemedySteps: []string{
			"Identify large files with: du -ahx / | sort -rh | head -n 20",
			"Prune unused container assets: docker system prune -a --volumes",
			"Clean rotated journal logs: journalctl --vacuum-size=500M",
		},
		QuickFixCmd: "journalctl --vacuum-size=500M",
	},
	"HOST-INO-001": {
		ID:         "HOST-INO-001",
		Title:      "High Inode Utilization",
		TargetType: model.TargetHost,
		Category:   "Disk Utilization",
		Severity:   model.SeverityCritical,
		Resource:   "filesystem:/",
		Symptom:    "Filesystem inode usage has exceeded warning (85%) or critical (95%) thresholds.",
		RootCause:  "Millions of tiny files (e.g. PHP sessions, mail queues, cache directories) exhausting filesystem metadata index.",
		RemedySteps: []string{
			"Find directories with high file counts: find / -xdev -type d -exec sh -c 'echo \"$(ls -1 \"$1\" | wc -l) $1\"' _ {} \\; | sort -rn | head -20",
			"Purge expired temporary files or sessions",
		},
	},
	"HOST-MEM-001": {
		ID:         "HOST-MEM-001",
		Title:      "Kernel OOM Killer Triggered",
		TargetType: model.TargetHost,
		Category:   "Memory Pressure",
		Severity:   model.SeverityCritical,
		Resource:   "kernel:dmesg",
		Symptom:    "Linux kernel invoked oom-killer to terminate high-memory processes due to memory exhaustion.",
		RootCause:  "Process memory leak or aggregate workload demands exceeding physical RAM plus available swap.",
		RemedySteps: []string{
			"Inspect OOM logs: dmesg -T | grep -i -E 'oom[-_]killer|killed process'",
			"Identify top memory consuming processes: ps aux --sort=-%mem | head -10",
			"Configure memory limits or increase system RAM/swap",
		},
	},
	"HOST-MEM-002": {
		ID:         "HOST-MEM-002",
		Title:      "High System Memory Utilization",
		TargetType: model.TargetHost,
		Category:   "Memory Pressure",
		Severity:   model.SeverityWarning,
		Resource:   "host:memory",
		Symptom:    "Available physical memory is below 15% (warning) or 5% (critical).",
		RootCause:  "Workloads consuming nearly all available RAM without sufficient headroom for buffer cache.",
		RemedySteps: []string{
			"Check top memory consumers: ps aux --sort=-%mem | head -n 10",
			"Tune process memory pools or add swap space",
		},
	},
	"HOST-MEM-003": {
		ID:         "HOST-MEM-003",
		Title:      "High Swap Memory Utilization",
		TargetType: model.TargetHost,
		Category:   "Memory Pressure",
		Severity:   model.SeverityWarning,
		Resource:   "host:swap",
		Symptom:    "Swap memory usage exceeds 80%, indicating sustained physical memory deficits.",
		RootCause:  "Insufficient physical RAM forcing kernel to continuously swap pages to disk, degrading I/O performance.",
		RemedySteps: []string{
			"Identify swapping processes via /proc/[pid]/smaps",
			"Evaluate swappiness sysctl (vm.swappiness)",
		},
	},
	"HOST-CPU-001": {
		ID:         "HOST-CPU-001",
		Title:      "High CPU Utilization / Load Average",
		TargetType: model.TargetHost,
		Category:   "Compute Saturation",
		Severity:   model.SeverityWarning,
		Resource:   "host:cpu",
		Symptom:    "CPU load average significantly exceeds available logical cores or active CPU exceeds 85%.",
		RootCause:  "Thread saturation, unconstrained CPU-bound workers, or blocked disk I/O (iowait).",
		RemedySteps: []string{
			"Check CPU-heavy processes: top -b -n 1 -o %CPU | head -n 20",
			"Inspect disk I/O wait with: vmstat 1 5 or iostat -xz 1 5",
		},
	},
	"HOST-ROF-001": {
		ID:         "HOST-ROF-001",
		Title:      "Read-Only Filesystem Detected",
		TargetType: model.TargetHost,
		Category:   "Storage Integrity",
		Severity:   model.SeverityCritical,
		Resource:   "filesystem:mounts",
		Symptom:    "Filesystem has remounted as read-only ('ro') preventing write operations.",
		RootCause:  "Underlying block storage corruption, storage controller timeout, or I/O failure triggering kernel safety remount.",
		RemedySteps: []string{
			"Inspect kernel logs: dmesg -T | grep -i -E 'ext4|xfs|read-only|remount'",
			"Schedule maintenance to unmount and run fsck on block device",
		},
	},
	"HOST-ZOM-001": {
		ID:         "HOST-ZOM-001",
		Title:      "Zombie Process Accumulation",
		TargetType: model.TargetHost,
		Category:   "Process Lifecycle",
		Severity:   model.SeverityWarning,
		Resource:   "host:procs",
		Symptom:    "Detected terminated processes that have not been reaped by their parent process.",
		RootCause:  "Parent process failed to call wait()/waitpid() or is hung.",
		RemedySteps: []string{
			"Identify parent process: ps -eo pid,ppid,stat,cmd | awk '$3 ~ /Z/'",
			"Restart parent process to let init/PID 1 reap zombie children",
		},
	},
	"HOST-NET-001": {
		ID:         "HOST-NET-001",
		Title:      "Network Interface Errors or Drops",
		TargetType: model.TargetHost,
		Category:   "Network Health",
		Severity:   model.SeverityWarning,
		Resource:   "net:interface",
		Symptom:    "Network interface shows increasing RX/TX packet drop or error counters.",
		RootCause:  "Network ring buffer exhaustion, duplex mismatch, MTU fragmentation, or physical NIC degradation.",
		RemedySteps: []string{
			"Check interface statistics: ip -s link show",
			"Inspect ring buffer sizes: ethtool -g <interface>",
		},
	},
	"HOST-DNS-001": {
		ID:         "HOST-DNS-001",
		Title:      "Host DNS Resolution Degradation",
		TargetType: model.TargetHost,
		Category:   "DNS Resolution",
		Severity:   model.SeverityCritical,
		Resource:   "dns:resolv.conf",
		Symptom:    "Host fails to resolve standard external or internal domain names, or resolution latency exceeds 2000ms.",
		RootCause:  "Upstream nameservers in /etc/resolv.conf unreachable, DNS port 53 blocked, or local resolver daemon crashed.",
		RemedySteps: []string{
			"Check nameservers in /etc/resolv.conf",
			"Test resolution with: dig @127.0.0.53 google.com or nslookup google.com",
			"Restart local resolver: systemctl restart systemd-resolved",
		},
	},
	"HOST-SYS-001": {
		ID:         "HOST-SYS-001",
		Title:      "Systemd Service Failed",
		TargetType: model.TargetHost,
		Category:   "Service Health",
		Severity:   model.SeverityCritical,
		Resource:   "systemd:unit",
		Symptom:    "One or more essential systemd units have entered 'failed' state.",
		RootCause:  "Service crash, missing configuration, failed dependency, or unhandled exception.",
		RemedySteps: []string{
			"Inspect failed units: systemctl --failed",
			"Read service logs: journalctl -u <unit> -e -n 50",
			"Restart service after fixing root cause: systemctl restart <unit>",
		},
	},

	// Docker
	"DOC-ALL-001": {
		ID:         "DOC-ALL-001",
		Title:      "Docker Engine Healthy",
		TargetType: model.TargetDocker,
		Category:   "Container Runtime",
		Severity:   model.SeverityPass,
		Resource:   "docker:daemon",
		Symptom:    "All monitored Docker containers are running and healthy.",
	},
	"DOC-EXT-137": {
		ID:         "DOC-EXT-137",
		Title:      "Container Terminated via OOM / SIGKILL (Exit 137)",
		TargetType: model.TargetDocker,
		Category:   "Memory Pressure",
		Severity:   model.SeverityCritical,
		Resource:   "docker:container",
		Symptom:    "Container exited with code 137 (128 + 9 = SIGKILL), typically sent by the OOM killer.",
		RootCause:  "Container memory limit (docker --memory or compose mem_limit) exceeded, or host kernel OOM killer selected the container.",
		RemedySteps: []string{
			"Inspect container exit reason: docker inspect <container_id> --format '{{.State.OOMKilled}}'",
			"Increase container memory limit in docker-compose or run command",
			"Profile memory consumption within application",
		},
	},
	"DOC-EXT-139": {
		ID:         "DOC-EXT-139",
		Title:      "Container Segmentation Fault (Exit 139)",
		TargetType: model.TargetDocker,
		Category:   "Application Crash",
		Severity:   model.SeverityCritical,
		Resource:   "docker:container",
		Symptom:    "Container crashed with exit code 139 (SIGSEGV).",
		RootCause:  "Application binary attempted an invalid memory access or native C extension crashed.",
		RemedySteps: []string{
			"Check container logs for stack trace: docker logs <container_id> --tail 100",
			"Verify compatible architecture and native dependency versions",
		},
	},
	"DOC-EXT-127": {
		ID:         "DOC-EXT-127",
		Title:      "Container Command Not Found (Exit 127)",
		TargetType: model.TargetDocker,
		Category:   "Configuration Error",
		Severity:   model.SeverityCritical,
		Resource:   "docker:container",
		Symptom:    "Container failed to start with exit code 127.",
		RootCause:  "ENTRYPOINT or CMD executable missing from container image filesystem or wrong PATH.",
		RemedySteps: []string{
			"Verify entrypoint script exists and has executable bit (+x)",
			"Verify shebang (e.g. #!/bin/sh instead of #!/bin/bash in alpine images)",
		},
	},
	"DOC-EXT-ERR": {
		ID:         "DOC-EXT-ERR",
		Title:      "Container Exited With Non-Zero Error Code",
		TargetType: model.TargetDocker,
		Category:   "Application Crash",
		Severity:   model.SeverityCritical,
		Resource:   "docker:container",
		Symptom:    "Container terminated unexpectedly with an error code.",
		RootCause:  "Uncaught runtime exception, failed startup assertion, or configuration error.",
		RemedySteps: []string{
			"Read container crash logs: docker logs <container_id> --tail 50",
		},
	},
	"DOC-HLT-001": {
		ID:         "DOC-HLT-001",
		Title:      "Container Healthcheck Failing",
		TargetType: model.TargetDocker,
		Category:   "Application Health",
		Severity:   model.SeverityCritical,
		Resource:   "docker:healthcheck",
		Symptom:    "Container has status 'unhealthy' due to repeated healthcheck failures.",
		RootCause:  "Application HTTP endpoint returning 5xx, database connection timeout, or slow response.",
		RemedySteps: []string{
			"Inspect healthcheck logs: docker inspect <container_id> --format '{{json .State.Health}}'",
			"Test health endpoint directly from host or another container",
		},
	},
	"DOC-RES-001": {
		ID:         "DOC-RES-001",
		Title:      "Container in Continuous Restart Loop",
		TargetType: model.TargetDocker,
		Category:   "Crash Loop",
		Severity:   model.SeverityCritical,
		Resource:   "docker:restart_loop",
		Symptom:    "Container has restarted repeatedly within the last few minutes.",
		RootCause:  "Application crashes immediately upon startup, restart policy (e.g. always) restarts it indefinitely.",
		RemedySteps: []string{
			"Examine crash logs: docker logs --tail 100 <container_id>",
			"Verify environment variables and required backing services (DB, Redis)",
		},
	},
	"DOC-DSK-001": {
		ID:         "DOC-DSK-001",
		Title:      "Docker Disk Space Reclaimable",
		TargetType: model.TargetDocker,
		Category:   "Disk Utilization",
		Severity:   model.SeverityWarning,
		Resource:   "docker:storage",
		Symptom:    "Unused Docker images, stopped containers, or dangling build caches are consuming excessive disk space.",
		RootCause:  "Automated CI/CD deployments pushing new tags without automated image prune policies.",
		RemedySteps: []string{
			"Run safe prune: docker system prune -f",
			"Clean dangling images: docker image prune -f",
		},
		QuickFixCmd: "docker system prune -f",
	},

	// Swarm
	"SWM-ALL-001": {
		ID:         "SWM-ALL-001",
		Title:      "Docker Swarm Healthy",
		TargetType: model.TargetSwarm,
		Category:   "Swarm Health",
		Severity:   model.SeverityPass,
		Resource:   "swarm:cluster",
		Symptom:    "All Swarm services and nodes are operating normally.",
	},
	"SWM-WRK-001": {
		ID:         "SWM-WRK-001",
		Title:      "Docker Swarm Worker Node",
		TargetType: model.TargetSwarm,
		Category:   "Cluster Role",
		Severity:   model.SeverityInfo,
		Resource:   "swarm:node",
		Symptom:    "Host is a Docker Swarm worker node; cluster manager API is not accessible locally.",
		RootCause:  "Normal Swarm worker node topology.",
		RemedySteps: []string{
			"Run swarm diagnostics from an active manager node or query swarm manager remotely",
		},
	},
	"SWM-REP-001": {
		ID:         "SWM-REP-001",
		Title:      "Swarm Service Replica Shortfall",
		TargetType: model.TargetSwarm,
		Category:   "Service Availability",
		Severity:   model.SeverityCritical,
		Resource:   "swarm:service",
		Symptom:    "Active running replicas are fewer than desired replicas.",
		RootCause:  "Tasks failing placement constraints, crashing on startup, or node resources exhausted.",
		RemedySteps: []string{
			"Inspect service tasks: docker service ps <service_name> --no-trunc",
			"Inspect service logs: docker service logs <service_name> --tail 50",
		},
	},
	"SWM-NOD-001": {
		ID:         "SWM-NOD-001",
		Title:      "Swarm Node Down / Unreachable",
		TargetType: model.TargetSwarm,
		Category:   "Node Health",
		Severity:   model.SeverityCritical,
		Resource:   "swarm:node",
		Symptom:    "One or more Swarm cluster nodes report status 'down'.",
		RootCause:  "Host hardware failure, network partition, or docker daemon crash on remote worker.",
		RemedySteps: []string{
			"Check node status: docker node ls",
			"Verify network connectivity and docker daemon status on the affected node",
		},
	},
	"SWM-NOD-002": {
		ID:         "SWM-NOD-002",
		Title:      "Swarm Node Availability Drained",
		TargetType: model.TargetSwarm,
		Category:   "Node Health",
		Severity:   model.SeverityWarning,
		Resource:   "swarm:node",
		Symptom:    "Swarm node is marked as 'drain' and will not accept tasks.",
		RootCause:  "Node was drained for maintenance and not un-drained.",
		RemedySteps: []string{
			"If maintenance is complete, activate node: docker node update --availability active <node_id>",
		},
	},

	// Kubernetes
	"K8S-ALL-001": {
		ID:         "K8S-ALL-001",
		Title:      "Kubernetes Cluster Healthy",
		TargetType: model.TargetKubernetes,
		Category:   "Cluster Health",
		Severity:   model.SeverityPass,
		Resource:   "k8s:cluster",
		Symptom:    "Kubernetes cluster API, nodes, and pods are operating normally.",
	},
	"K8S-API-001": {
		ID:         "K8S-API-001",
		Title:      "Kubernetes API Unreachable",
		TargetType: model.TargetKubernetes,
		Category:   "Control Plane",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:apiserver",
		Symptom:    "Unable to connect to Kubernetes API server via kubectl.",
		RootCause:  "Kubeconfig invalid, control-plane nodes down, API server certificate expired, or network firewall.",
		RemedySteps: []string{
			"Verify kubeconfig and cluster endpoint: kubectl cluster-info",
			"Check control-plane status and kube-apiserver container logs",
		},
	},
	"K8S-POD-001": {
		ID:         "K8S-POD-001",
		Title:      "Pod in CrashLoopBackOff",
		TargetType: model.TargetKubernetes,
		Category:   "Workload Stability",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pod",
		Symptom:    "Container repeatedly terminates shortly after starting, Kubernetes exponential backoff delays restarts.",
		RootCause:  "Application error, unhandled exception, bad configuration, or missing dependency.",
		RemedySteps: []string{
			"Read pod logs: kubectl logs <pod> -c <container> --previous",
			"Check pod events: kubectl describe pod <pod>",
		},
	},
	"K8S-POD-002": {
		ID:         "K8S-POD-002",
		Title:      "Pod Terminated with OOMKilled",
		TargetType: model.TargetKubernetes,
		Category:   "Memory Limits",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pod",
		Symptom:    "Container exceeded its memory limit (resources.limits.memory) and was terminated by cgroup OOM killer.",
		RootCause:  "Application memory leak, insufficient resource limit allocation, or JVM heap misconfiguration.",
		RemedySteps: []string{
			"Inspect pod resource limits: kubectl get pod <pod> -o yaml | grep -A 5 resources",
			"Increase container memory limit in deployment manifest",
			"Analyze memory profiling / heap dump",
		},
	},
	"K8S-POD-003": {
		ID:         "K8S-POD-003",
		Title:      "Pod Image Pull Failure (ImagePullBackOff)",
		TargetType: model.TargetKubernetes,
		Category:   "Image Delivery",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pod",
		Symptom:    "Kubelet cannot pull the specified container image.",
		RootCause:  "Image tag does not exist, registry authentication failed (missing imagePullSecrets), or network firewall blocks registry.",
		RemedySteps: []string{
			"Describe pod to see failure reason: kubectl describe pod <pod>",
			"Verify image tag exists in container registry",
			"Verify imagePullSecrets exists in the pod's namespace",
		},
	},
	"K8S-POD-004": {
		ID:         "K8S-POD-004",
		Title:      "Pod Stuck in ContainerCreating",
		TargetType: model.TargetKubernetes,
		Category:   "Pod Lifecycle",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pod",
		Symptom:    "Pod remains in ContainerCreating state for longer than 3 minutes.",
		RootCause:  "PVC mount timeout, missing ConfigMap/Secret volume, or CNI IP address exhaustion.",
		RemedySteps: []string{
			"Check events: kubectl describe pod <pod>",
			"Verify referenced Secrets, ConfigMaps, and PVCs exist and are bound",
		},
	},
	"K8S-POD-005": {
		ID:         "K8S-POD-005",
		Title:      "Excessive Pod Restarts",
		TargetType: model.TargetKubernetes,
		Category:   "Workload Stability",
		Severity:   model.SeverityWarning,
		Resource:   "k8s:pod",
		Symptom:    "Pod has restarted multiple times despite currently reporting Running state.",
		RootCause:  "Intermittent segfaults, failed liveness probes, or sporadic memory spikes.",
		RemedySteps: []string{
			"Check previous container logs: kubectl logs <pod> -p",
			"Review livenessProbe configuration and timeout settings",
		},
	},
	"K8S-POD-006": {
		ID:         "K8S-POD-006",
		Title:      "Pod Stuck in Pending (Unschedulable)",
		TargetType: model.TargetKubernetes,
		Category:   "Scheduler",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pod",
		Symptom:    "Pod cannot be scheduled onto any cluster node.",
		RootCause:  "Insufficient CPU/memory on nodes, node affinity/taint mismatches, or PVC binding wait.",
		RemedySteps: []string{
			"Read scheduler error: kubectl describe pod <pod> | grep -A 5 Events",
			"Check cluster node allocatable resources: kubectl describe nodes",
		},
	},
	"K8S-POD-007": {
		ID:         "K8S-POD-007",
		Title:      "Pod Stuck in Terminating",
		TargetType: model.TargetKubernetes,
		Category:   "Pod Lifecycle",
		Severity:   model.SeverityWarning,
		Resource:   "k8s:pod",
		Symptom:    "Pod has been terminating for longer than its grace period.",
		RootCause:  "Unresponsive preStop hook, blocked finalizer, or deadlocked storage volume unmount.",
		RemedySteps: []string{
			"Inspect pod finalizers: kubectl get pod <pod> -o jsonpath='{.metadata.finalizers}'",
			"Force delete if process is confirmed dead: kubectl delete pod <pod> --force --grace-period=0",
		},
	},
	"K8S-SVC-001": {
		ID:         "K8S-SVC-001",
		Title:      "Service Has Zero Active Endpoints",
		TargetType: model.TargetKubernetes,
		Category:   "Networking",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:service",
		Symptom:    "Kubernetes Service has no backing pod endpoints to route traffic to.",
		RootCause:  "Service selector labels do not match pod template labels, or all matching pods are dead/unhealthy.",
		RemedySteps: []string{
			"Compare service selector with pod labels: kubectl get svc <svc> -o yaml and kubectl get pods --show-labels",
			"Check endpoints: kubectl get endpoints <svc>",
		},
	},
	"K8S-SVC-002": {
		ID:         "K8S-SVC-002",
		Title:      "Mismatched Service TargetPort",
		TargetType: model.TargetKubernetes,
		Category:   "Networking",
		Severity:   model.SeverityWarning,
		Resource:   "k8s:service",
		Symptom:    "Service points to a targetPort that is not exposed or declared on target pod containers.",
		RootCause:  "Typo in service port specification or outdated container port configuration.",
		RemedySteps: []string{
			"Review targetPort in Service and containerPort in Deployment",
		},
	},
	"K8S-ING-001": {
		ID:         "K8S-ING-001",
		Title:      "Ingress Refers to Missing Service",
		TargetType: model.TargetKubernetes,
		Category:   "Ingress Routing",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:ingress",
		Symptom:    "Ingress rule points to a backend Service name that does not exist in the namespace.",
		RootCause:  "Service was renamed, deleted, or typographical error in Ingress spec.",
		RemedySteps: []string{
			"Inspect ingress spec: kubectl get ingress <ingress> -o yaml",
			"Verify backend service exists: kubectl get svc -n <namespace>",
		},
	},
	"K8S-ING-002": {
		ID:         "K8S-ING-002",
		Title:      "Ingress Refers to Missing TLS Secret",
		TargetType: model.TargetKubernetes,
		Category:   "Ingress TLS",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:ingress",
		Symptom:    "Ingress spec specifies a secretName for TLS termination that cannot be found.",
		RootCause:  "Cert-manager certificate generation failed, secret deleted, or wrong namespace.",
		RemedySteps: []string{
			"Verify secret exists: kubectl get secret <secretName> -n <namespace>",
			"If using cert-manager, check certificate status: kubectl describe certificate -n <namespace>",
		},
	},
	"K8S-DNS-001": {
		ID:         "K8S-DNS-001",
		Title:      "CoreDNS Unhealthy or Missing in Cluster",
		TargetType: model.TargetKubernetes,
		Category:   "Cluster DNS",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:coredns",
		Symptom:    "Cluster DNS pods (CoreDNS / kube-dns) are not running, ready, or discovered.",
		RootCause:  "CoreDNS deployment scaled to 0, pods crashed, or CNI networking failure prevents pod-to-pod DNS.",
		RemedySteps: []string{
			"Check CoreDNS pods: kubectl get pods -n kube-system -l k8s-app=kube-dns",
			"Check CoreDNS logs: kubectl logs -n kube-system -l k8s-app=kube-dns",
		},
	},
	"K8S-PVC-001": {
		ID:         "K8S-PVC-001",
		Title:      "PersistentVolumeClaim Unbound / Pending",
		TargetType: model.TargetKubernetes,
		Category:   "Storage",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pvc",
		Symptom:    "PVC remains in Pending status and cannot bind a PersistentVolume.",
		RootCause:  "StorageClass does not exist, CSI driver provisioner failure, or no available PVs match access modes.",
		RemedySteps: []string{
			"Inspect PVC events: kubectl describe pvc <pvc_name>",
			"Verify storage classes: kubectl get storageclass",
		},
	},
	"K8S-NOD-001": {
		ID:         "K8S-NOD-001",
		Title:      "Kubernetes Node NotReady",
		TargetType: model.TargetKubernetes,
		Category:   "Node Health",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:node",
		Symptom:    "Kubernetes node reports Ready condition as False or Unknown.",
		RootCause:  "Kubelet stopped, node network unreachable, or container runtime crashed.",
		RemedySteps: []string{
			"Describe node: kubectl describe node <node>",
			"SSH to node and check kubelet service: systemctl status kubelet",
		},
	},
	"K8S-NOD-002": {
		ID:         "K8S-NOD-002",
		Title:      "Kubernetes Node Under Pressure",
		TargetType: model.TargetKubernetes,
		Category:   "Node Pressure",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:node",
		Symptom:    "Node reports MemoryPressure, DiskPressure, or PIDPressure.",
		RootCause:  "Node physical resources exhausted, kubelet will begin evicting pods.",
		RemedySteps: []string{
			"Describe node to check pressure condition: kubectl describe node <node>",
			"Investigate node resource consumers: kubectl top nodes and kubectl top pods -A",
		},
	},

	// Security
	"SEC-FIL-001": {
		ID:         "SEC-FIL-001",
		Title:      "Insecure File Permissions on Sensitive System Files",
		TargetType: model.TargetSecurity,
		Category:   "File Permissions",
		Severity:   model.SeverityCritical,
		Resource:   "file:/etc/shadow",
		Symptom:    "Sensitive configuration or credential file (/etc/shadow, /etc/sudoers) has world-writable or over-permissive bits.",
		RootCause:  "Misconfigured umask or manual permission modification exposing credentials to unprivileged local users.",
		RemedySteps: []string{
			"Restore secure file permissions: chmod 0640 /etc/shadow && chmod 0644 /etc/passwd",
		},
		QuickFixCmd: "chmod 0640 /etc/shadow 2>/dev/null; chmod 0644 /etc/passwd 2>/dev/null",
	},
	"SEC-DOC-001": {
		ID:         "SEC-DOC-001",
		Title:      "Container Running as Root User",
		TargetType: model.TargetSecurity,
		Category:   "Least Privilege",
		Severity:   model.SeverityWarning,
		Resource:   "docker:user",
		Symptom:    "Container runs as UID 0 (root) instead of a dedicated non-root user.",
		RootCause:  "Docker image does not specify USER directive in Dockerfile.",
		RemedySteps: []string{
			"Add 'USER 10001:10001' or dedicated application user to Dockerfile",
			"Run container with --user flag: docker run --user 1000:1000 ...",
		},
	},
	"SEC-DOC-002": {
		ID:         "SEC-DOC-002",
		Title:      "Container Running in Privileged Mode",
		TargetType: model.TargetSecurity,
		Category:   "Container Isolation",
		Severity:   model.SeverityCritical,
		Resource:   "docker:privileged",
		Symptom:    "Container has privileged: true, granting near-total access to host devices and kernel capabilities.",
		RootCause:  "Overly broad permissions granted instead of fine-grained Linux capabilities (cap-add).",
		RemedySteps: []string{
			"Remove 'privileged: true' from container configuration",
			"Add only required specific capabilities: --cap-add=NET_ADMIN",
		},
	},
	"SEC-DOC-003": {
		ID:         "SEC-DOC-003",
		Title:      "Sensitive Host Path Mounted in Container",
		TargetType: model.TargetSecurity,
		Category:   "Filesystem Isolation",
		Severity:   model.SeverityCritical,
		Resource:   "docker:mount",
		Symptom:    "Container mounts sensitive host path like /var/run/docker.sock, /, or /etc.",
		RootCause:  "Mounting docker.sock grants container root-equivalent control of the Docker daemon and the host.",
		RemedySteps: []string{
			"Remove docker.sock or root filesystem mounts from untrusted containers",
			"Use sidecar architecture or proxy APIs with RBAC instead of raw socket sharing",
		},
	},
	"SEC-SSH-001": {
		ID:         "SEC-SSH-001",
		Title:      "SSH Permits Direct Root Login",
		TargetType: model.TargetSecurity,
		Category:   "Authentication & Access Control",
		Severity:   model.SeverityCritical,
		Resource:   "file:/etc/ssh/sshd_config",
		Symptom:    "Directive 'PermitRootLogin yes' is enabled in sshd_config.",
		RootCause:  "Direct root login allows brute-force attacks against the root account without audit trail.",
		RemedySteps: []string{
			"Set 'PermitRootLogin prohibit-password' or 'no' in /etc/ssh/sshd_config",
			"Reload sshd: systemctl reload sshd",
		},
		QuickFixCmd: "sed -i 's/^PermitRootLogin yes/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config && systemctl reload sshd",
	},
	"SEC-SSH-002": {
		ID:         "SEC-SSH-002",
		Title:      "SSH Password Authentication Allowed",
		TargetType: model.TargetSecurity,
		Category:   "Authentication Hardening",
		Severity:   model.SeverityWarning,
		Resource:   "file:/etc/ssh/sshd_config",
		Symptom:    "Password authentication is enabled instead of enforcing public key authentication.",
		RootCause:  "Passwords are vulnerable to brute-force credential attacks.",
		RemedySteps: []string{
			"Deploy SSH public keys for authorized engineers",
			"Set 'PasswordAuthentication no' in /etc/ssh/sshd_config and reload sshd",
		},
	},
	"SEC-CRT-001": {
		ID:         "SEC-CRT-001",
		Title:      "TLS Certificate Expiring Soon or Expired",
		TargetType: model.TargetSecurity,
		Category:   "Certificates & TLS",
		Severity:   model.SeverityCritical,
		Resource:   "cert:tls",
		Symptom:    "TLS certificate has expired or expires within 14 days, risking service outages and browser security warnings.",
		RootCause:  "Automated renewal (e.g. certbot cron or cert-manager) failed or was not configured.",
		RemedySteps: []string{
			"Renew certificate manually or run: certbot renew",
			"Check certificate renewal cron / timer logs",
		},
		QuickFixCmd: "certbot renew",
	},
	"SEC-CRT-002": {
		ID:         "SEC-CRT-002",
		Title:      "TLS Certificate Endpoint Verification Failed",
		TargetType: model.TargetSecurity,
		Category:   "Certificates & TLS",
		Severity:   model.SeverityWarning,
		Resource:   "tls:endpoint",
		Symptom:    "Unable to complete TLS handshake or verify certificate validity for target host:port.",
		RootCause:  "Target service not listening with TLS, self-signed certificate untrusted, or port closed.",
		RemedySteps: []string{
			"Verify service TLS configuration and port",
		},
	},
	"SEC-PRT-001": {
		ID:         "SEC-PRT-001",
		Title:      "Sensitive Service Exposed Externally",
		TargetType: model.TargetSecurity,
		Category:   "Network Exposure",
		Severity:   model.SeverityCritical,
		Resource:   "tcp:port",
		Symptom:    "Internal database or management port (e.g. 6379 Redis, 2375 Docker, 27017 MongoDB) is bound to 0.0.0.0 or external IP.",
		RootCause:  "Service configured without bind address isolation (bind 127.0.0.1) or missing firewall rules.",
		RemedySteps: []string{
			"Reconfigure service to bind strictly to localhost (127.0.0.1)",
			"Block external access using firewall (ufw, iptables, cloud security groups)",
		},
	},
	"SEC-K8S-001": {
		ID:         "SEC-K8S-001",
		Title:      "Privileged Pod Detected in Cluster",
		TargetType: model.TargetSecurity,
		Category:   "Cluster Security",
		Severity:   model.SeverityCritical,
		Resource:   "k8s:pod",
		Symptom:    "Pod runs with securityContext.privileged: true, bypassing container isolation.",
		RootCause:  "Misconfigured pod manifest granting root-equivalent cluster node access.",
		RemedySteps: []string{
			"Remove privileged: true from pod spec",
			"Enforce Pod Security Standards (Baseline or Restricted)",
		},
	},
	"SEC-K8S-002": {
		ID:         "SEC-K8S-002",
		Title:      "Pod Lacks Resource Limits",
		TargetType: model.TargetSecurity,
		Category:   "Resource Quotas",
		Severity:   model.SeverityWarning,
		Resource:   "k8s:pod",
		Symptom:    "Pod containers do not specify CPU or memory limits.",
		RootCause:  "Missing resources.limits block in container specification.",
		RemedySteps: []string{
			"Define resources.limits.cpu and resources.limits.memory in pod template",
			"Configure LimitRange in the namespace to enforce default limits",
		},
	},
}

// GetCatalogFinding retrieves standard rule metadata for a given rule ID.
func GetCatalogFinding(id string) (model.Finding, bool) {
	key := strings.ToUpper(strings.TrimSpace(id))
	f, ok := standardCatalog[key]
	return f, ok
}

// AllCatalogFindings returns all standard rule definitions.
func AllCatalogFindings() []model.Finding {
	res := make([]model.Finding, 0, len(standardCatalog))
	for _, f := range standardCatalog {
		res = append(res, f)
	}
	return res
}
